// Package graphql — generated.go provides the executable schema wiring
// that would normally be auto-generated by `gqlgen generate`.
//
// This is a hand-written implementation that directly maps GraphQL
// operations to resolver methods, avoiding the gqlgen code generation
// step for build simplicity. It uses the graphql-go handler from the
// 99designs/gqlgen ecosystem for HTTP transport.
package graphql

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/aminul01-g/intellireview/services/analysis-history/internal/store"
	"go.uber.org/zap"
)

// Config holds resolver references for the executable schema.
type Config struct {
	Resolvers ResolverInterface
}

// ResolverInterface defines the methods that resolvers must implement.
type ResolverInterface interface {
	AnalysisHistory(ctx context.Context, repositoryID int, first int, after *string, startDate, endDate *time.Time) (*AnalysisHistoryConnection, error)
	Hotspots(ctx context.Context, repositoryID int, limit int) ([]Hotspot, error)
	WeeklyTrend(ctx context.Context, repositoryID int, weeks int) ([]WeeklySnapshot, error)
}

// ─── GraphQL Request/Response Types ─────────────────────────────────

// GraphQLRequest represents an incoming GraphQL HTTP request.
type GraphQLRequest struct {
	Query         string                 `json:"query"`
	OperationName string                 `json:"operationName"`
	Variables     map[string]interface{} `json:"variables"`
}

// GraphQLResponse represents an outgoing GraphQL HTTP response.
type GraphQLResponse struct {
	Data   interface{}    `json:"data,omitempty"`
	Errors []GraphQLError `json:"errors,omitempty"`
}

// GraphQLError represents a GraphQL error.
type GraphQLError struct {
	Message string `json:"message"`
}

// ─── Executable Schema (HTTP Handler) ───────────────────────────────

// ExecutableSchema is a simple GraphQL executor that parses incoming
// queries and dispatches to the appropriate resolver methods.
type ExecutableSchema struct {
	resolver ResolverInterface
	logger   *zap.Logger
}

// NewExecutableSchema creates a new schema executor with the given config.
func NewExecutableSchema(cfg Config) *ExecutableSchema {
	r, ok := cfg.Resolvers.(*Resolver)
	if !ok {
		return &ExecutableSchema{resolver: cfg.Resolvers}
	}
	return &ExecutableSchema{
		resolver: cfg.Resolvers,
		logger:   r.Logger,
	}
}

// ServeHTTP implements http.Handler for the GraphQL endpoint.
func (es *ExecutableSchema) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodOptions {
		w.WriteHeader(http.StatusOK)
		return
	}

	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req GraphQLRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, "invalid JSON request body", http.StatusBadRequest)
		return
	}

	ctx := r.Context()
	data, errs := es.execute(ctx, req)

	resp := GraphQLResponse{Data: data}
	if len(errs) > 0 {
		resp.Errors = errs
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(resp)
}

// execute dispatches a GraphQL request to the appropriate resolver.
func (es *ExecutableSchema) execute(ctx context.Context, req GraphQLRequest) (interface{}, []GraphQLError) {
	query := strings.TrimSpace(req.Query)
	vars := req.Variables
	if vars == nil {
		vars = make(map[string]interface{})
	}

	result := make(map[string]interface{})
	var errors []GraphQLError

	// Simple query parser — matches the three root query fields
	if containsField(query, "analysisHistory") {
		repoID := getIntVar(vars, "repositoryId", 0)
		first := getIntVar(vars, "first", 20)
		after := getStringVar(vars, "after")
		startDate := getTimeVar(vars, "startDate")
		endDate := getTimeVar(vars, "endDate")

		conn, err := es.resolver.AnalysisHistory(ctx, repoID, first, after, startDate, endDate)
		if err != nil {
			errors = append(errors, GraphQLError{Message: err.Error()})
		} else {
			result["analysisHistory"] = conn
		}
	}

	if containsField(query, "hotspots") {
		repoID := getIntVar(vars, "repositoryId", 0)
		limit := getIntVar(vars, "limit", 10)

		hotspots, err := es.resolver.Hotspots(ctx, repoID, limit)
		if err != nil {
			errors = append(errors, GraphQLError{Message: err.Error()})
		} else {
			result["hotspots"] = hotspots
		}
	}

	if containsField(query, "weeklyTrend") {
		repoID := getIntVar(vars, "repositoryId", 0)
		weeks := getIntVar(vars, "weeks", 12)

		trend, err := es.resolver.WeeklyTrend(ctx, repoID, weeks)
		if err != nil {
			errors = append(errors, GraphQLError{Message: err.Error()})
		} else {
			result["weeklyTrend"] = trend
		}
	}

	if len(result) == 0 && len(errors) == 0 {
		errors = append(errors, GraphQLError{Message: "no recognized query fields found"})
	}

	return result, errors
}

// ─── Cursor Encoding/Decoding ───────────────────────────────────────

// EncodeCursor encodes a time.Time as a base64 cursor string.
func EncodeCursor(t time.Time) string {
	return base64.StdEncoding.EncodeToString([]byte(t.Format(time.RFC3339Nano)))
}

// DecodeCursor decodes a base64 cursor string back to a time.Time.
func DecodeCursor(cursor string) (time.Time, error) {
	data, err := base64.StdEncoding.DecodeString(cursor)
	if err != nil {
		return time.Time{}, fmt.Errorf("invalid cursor encoding: %w", err)
	}
	t, err := time.Parse(time.RFC3339Nano, string(data))
	if err != nil {
		return time.Time{}, fmt.Errorf("invalid cursor timestamp: %w", err)
	}
	return t, nil
}

// ─── Store → GraphQL Type Converters ────────────────────────────────

// ToGraphQLSnapshot converts a store.MetricsSnapshot to a GraphQL MetricsSnapshot.
func ToGraphQLSnapshot(s store.MetricsSnapshot) MetricsSnapshot {
	return MetricsSnapshot{
		RecordedAt:         s.RecordedAt,
		RepositoryID:       s.RepositoryID,
		AnalysisRunID:      s.AnalysisRunID,
		CodeHealthScore:    s.CodeHealthScore,
		TechnicalDebtHours: s.TechnicalDebtHours,
		TechnicalDebtDays:  s.TechnicalDebtHours / 8.0, // SonarQube 8-hour day
		TotalIssues:        s.TotalIssues,
		CriticalCount:      s.CriticalCount,
		HighCount:          s.HighCount,
		MediumCount:        s.MediumCount,
		LowCount:           s.LowCount,
		LinesOfCode:        s.LinesOfCode,
		AvgComplexity:      s.AvgComplexity,
		MaxComplexity:      s.MaxComplexity,
		MaintainabilityIdx: s.MaintainabilityIndex,
		DuplicationPct:     s.DuplicationPct,
		Grades: DimensionGrades{
			Reliability:     s.ReliabilityGrade,
			Security:        s.SecurityGrade,
			Maintainability: s.MaintainabilityGrade,
			Coverage:        s.CoverageGrade,
		},
	}
}

// ToGraphQLHotspot converts a store.Hotspot to a GraphQL Hotspot.
func ToGraphQLHotspot(h store.Hotspot) Hotspot {
	return Hotspot{
		FilePath:                h.FilePath,
		CommitFrequency:         h.CommitFrequency,
		AvgCyclomaticComplexity: h.AvgCyclomaticComplexity,
		MaxCyclomaticComplexity: h.MaxCyclomaticComplexity,
		HotspotScore:            h.HotspotScore,
		LastAnalyzedAt:          h.LastAnalyzedAt,
	}
}

// ToGraphQLWeekly converts a store.WeeklySnapshot to a GraphQL WeeklySnapshot.
func ToGraphQLWeekly(ws store.WeeklySnapshot) WeeklySnapshot {
	return WeeklySnapshot{
		Week:                  ws.Week,
		AvgHealth:             ws.AvgHealth,
		TotalDebtHours:        ws.TotalDebtHours,
		PeakIssues:            ws.PeakIssues,
		LatestReliability:     ws.LatestReliability,
		LatestSecurity:        ws.LatestSecurity,
		LatestMaintainability: ws.LatestMaintainability,
	}
}

// ─── Helpers ────────────────────────────────────────────────────────

func containsField(query, field string) bool {
	return strings.Contains(query, field)
}

func getIntVar(vars map[string]interface{}, key string, fallback int) int {
	v, ok := vars[key]
	if !ok {
		return fallback
	}
	switch val := v.(type) {
	case float64:
		return int(val)
	case int:
		return val
	case string:
		n, err := strconv.Atoi(val)
		if err != nil {
			return fallback
		}
		return n
	default:
		return fallback
	}
}

func getStringVar(vars map[string]interface{}, key string) *string {
	v, ok := vars[key]
	if !ok {
		return nil
	}
	s, ok := v.(string)
	if !ok || s == "" {
		return nil
	}
	return &s
}

func getTimeVar(vars map[string]interface{}, key string) *time.Time {
	v, ok := vars[key]
	if !ok {
		return nil
	}
	s, ok := v.(string)
	if !ok || s == "" {
		return nil
	}
	t, err := time.Parse(time.RFC3339, s)
	if err != nil {
		return nil
	}
	return &t
}

func writeError(w http.ResponseWriter, msg string, status int) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(GraphQLResponse{
		Errors: []GraphQLError{{Message: msg}},
	})
}
