// Package graphql provides the GraphQL types and schema configuration
// for the analysis-history service.
//
// In a production setup, most of these types would be auto-generated by
// `gqlgen generate`. Here we define them manually to keep the service
// self-contained without requiring the gqlgen CLI during builds.
package graphql

import (
	"time"
)

// ─── GraphQL Model Types ────────────────────────────────────────────

// MetricsSnapshot is the GraphQL representation of a single metrics history entry.
type MetricsSnapshot struct {
	RecordedAt         time.Time       `json:"recordedAt"`
	RepositoryID       int             `json:"repositoryId"`
	AnalysisRunID      int             `json:"analysisRunId"`
	CodeHealthScore    float64         `json:"codeHealthScore"`
	TechnicalDebtHours float64         `json:"technicalDebtHours"`
	TechnicalDebtDays  float64         `json:"technicalDebtDays"`
	TotalIssues        int             `json:"totalIssues"`
	CriticalCount      int             `json:"criticalCount"`
	HighCount          int             `json:"highCount"`
	MediumCount        int             `json:"mediumCount"`
	LowCount           int             `json:"lowCount"`
	LinesOfCode        int             `json:"linesOfCode"`
	AvgComplexity      float64         `json:"avgComplexity"`
	MaxComplexity      int             `json:"maxComplexity"`
	MaintainabilityIdx float64         `json:"maintainabilityIndex"`
	DuplicationPct     float64         `json:"duplicationPct"`
	Grades             DimensionGrades `json:"grades"`
}

// DimensionGrades holds A/B/C/D grades for each quality dimension.
type DimensionGrades struct {
	Reliability     string `json:"reliability"`
	Security        string `json:"security"`
	Maintainability string `json:"maintainability"`
	Coverage        string `json:"coverage"`
}

// AnalysisHistoryConnection is the Relay-style paginated response for history queries.
type AnalysisHistoryConnection struct {
	Edges      []AnalysisHistoryEdge `json:"edges"`
	PageInfo   PageInfo              `json:"pageInfo"`
	TotalCount int                   `json:"totalCount"`
}

// AnalysisHistoryEdge is a single edge in the paginated connection.
type AnalysisHistoryEdge struct {
	Cursor string          `json:"cursor"`
	Node   MetricsSnapshot `json:"node"`
}

// PageInfo provides pagination metadata.
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor"`
	EndCursor       *string `json:"endCursor"`
}

// Hotspot is the GraphQL representation of a hotspot file entry.
type Hotspot struct {
	FilePath                string    `json:"filePath"`
	CommitFrequency         int       `json:"commitFrequency"`
	AvgCyclomaticComplexity float64   `json:"avgCyclomaticComplexity"`
	MaxCyclomaticComplexity int       `json:"maxCyclomaticComplexity"`
	HotspotScore            float64   `json:"hotspotScore"`
	LastAnalyzedAt          time.Time `json:"lastAnalyzedAt"`
}

// WeeklySnapshot is the GraphQL representation of a weekly rollup from the continuous aggregate.
type WeeklySnapshot struct {
	Week                  time.Time `json:"week"`
	AvgHealth             float64   `json:"avgHealth"`
	TotalDebtHours        float64   `json:"totalDebtHours"`
	PeakIssues            int       `json:"peakIssues"`
	LatestReliability     string    `json:"latestReliability"`
	LatestSecurity        string    `json:"latestSecurity"`
	LatestMaintainability string    `json:"latestMaintainability"`
}
