import React, { useState } from 'react'
import {
  createColumnHelper,
  flexRender,
  getCoreRowModel,
  useReactTable,
} from '@tanstack/react-table'
import { useScanHistory, useScanReport, TransformedScanData } from '@/hooks/useScanHistory'
import * as Dialog from '@radix-ui/react-dialog'
import * as LucideIcons from 'lucide-react'
const { X, FileCode, RefreshCw, Clock, AlertTriangle, Shield, Info } = LucideIcons as any
const ChevronDown = (LucideIcons as any).ChevronDown || ((props: any) => <span {...props}>▼</span>)
const ChevronRight = (LucideIcons as any).ChevronRight || ((props: any) => <span {...props}>▶</span>)
const Download = (LucideIcons as any).Download || ((props: any) => <span {...props}>⬇</span>)
const FileText = (LucideIcons as any).FileText || FileCode

// --- EXPORT UTILITY ---
function exportAnalysisMarkdown(analysis: any) {
  const issues = analysis?.originalAnalysis?.issues || []
  const metrics = analysis?.originalAnalysis?.metrics
  const code = analysis?.originalAnalysis?.original_code
  const date = analysis?.date ? new Date(analysis.date).toLocaleString() : 'Unknown'

  const filteredIssues = issues.filter((i: any) => i.type !== 'ai_overview')

  let md = `# IntelliReview Analysis Report\n\n`
  md += `**Date:** ${date}  \n`
  md += `**Language:** ${analysis?.language || 'Unknown'}  \n`
  md += `**Health Score:** ${analysis?.healthScore ?? '-'}/100  \n`
  md += `**Issues Found:** ${filteredIssues.length}  \n\n`

  if (metrics) {
    md += `## Metrics\n\n`
    md += `| Metric | Value |\n|--------|-------|\n`
    md += `| Lines of Code | ${metrics.lines_of_code ?? '-'} |\n`
    md += `| Cyclomatic Complexity | ${metrics.complexity?.toFixed(1) ?? '-'} |\n`
    md += `| Maintainability Index | ${metrics.maintainability_index?.toFixed(1) ?? '-'} |\n\n`
  }

  if (filteredIssues.length > 0) {
    md += `## Issues\n\n`
    md += `| # | Severity | Message | CWE | Line |\n|---|----------|---------|-----|------|\n`
    filteredIssues.forEach((issue: any, idx: number) => {
      md += `| ${idx + 1} | ${(issue.severity || 'info').toUpperCase()} | ${issue.message || '-'} | ${issue.cwe || '-'} | ${issue.line || '-'} |\n`
    })
    md += '\n'
  }

  if (code) {
    md += `## Analyzed Code\n\n\`\`\`python\n${code}\n\`\`\`\n`
  }

  md += `\n---\n*Generated by IntelliReview at ${new Date().toISOString()}*\n`

  // Trigger download
  const blob = new Blob([md], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `intellireview-report-${analysis?.id || Date.now()}.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// --- SEVERITY BADGE ---
const SeverityBadge = ({ severity }: { severity: string }) => {
  const config: Record<string, { bg: string; text: string; label: string }> = {
    critical: { bg: 'bg-red-500/15 border-red-500/30', text: 'text-red-400', label: 'Critical' },
    high: { bg: 'bg-orange-500/15 border-orange-500/30', text: 'text-orange-400', label: 'High' },
    medium: { bg: 'bg-yellow-500/15 border-yellow-500/30', text: 'text-yellow-400', label: 'Medium' },
    low: { bg: 'bg-blue-500/15 border-blue-500/30', text: 'text-blue-400', label: 'Low' },
    info: { bg: 'bg-slate-500/15 border-slate-500/30', text: 'text-slate-400', label: 'Info' },
  }
  const c = config[severity?.toLowerCase()] || config.info
  return (
    <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider border ${c.bg} ${c.text}`}>
      {c.label}
    </span>
  )
}

// --- EXPANDABLE ISSUE ROW ---
const IssueRow = ({ issue }: { issue: any }) => (
  <div className="flex items-start gap-3 py-2 px-3 rounded-md hover:bg-muted/30 transition-colors">
    <SeverityBadge severity={issue.severity} />
    <div className="flex-1 min-w-0">
      <p className="text-sm text-foreground truncate">{issue.message}</p>
      {issue.suggestion && (
        <p className="text-xs text-muted-foreground mt-0.5 truncate">💡 {issue.suggestion}</p>
      )}
    </div>
    <div className="flex items-center gap-2 text-xs text-muted-foreground shrink-0">
      {issue.line > 0 && <span className="font-mono">L{issue.line}</span>}
      {issue.cwe && (
        <a
          href={issue.reference_url || `https://cwe.mitre.org/data/definitions/${issue.cwe.replace('CWE-', '')}.html`}
          target="_blank"
          rel="noopener noreferrer"
          className="text-primary hover:underline font-mono"
        >
          {issue.cwe}
        </a>
      )}
    </div>
  </div>
)

// --- EXPANDED ROW DETAIL ---
const ExpandedDetail = ({ analysis }: { analysis: any }) => {
  const issues = analysis?.originalAnalysis?.issues || []
  const metrics = analysis?.originalAnalysis?.metrics
  const code = analysis?.originalAnalysis?.original_code

  const severityCounts = issues.reduce((acc: Record<string, number>, i: any) => {
    const s = i.severity?.toLowerCase() || 'info'
    acc[s] = (acc[s] || 0) + 1
    return acc
  }, {})

  return (
    <div className="px-4 py-4 bg-muted/10 border-t border-border/50 animate-in fade-in slide-in-from-top-2 duration-300">
      {/* Severity summary bar */}
      <div className="flex items-center gap-3 mb-4 flex-wrap">
        {Object.entries(severityCounts).map(([sev, count]) => (
          <div key={sev} className="flex items-center gap-1.5">
            <SeverityBadge severity={sev} />
            <span className="text-xs text-muted-foreground font-medium">×{count as number}</span>
          </div>
        ))}
        {metrics && (
          <div className="ml-auto flex items-center gap-4 text-xs text-muted-foreground">
            <span>Lines: <strong className="text-foreground">{metrics.lines_of_code}</strong></span>
            <span>Complexity: <strong className="text-foreground">{metrics.complexity?.toFixed(1)}</strong></span>
            <span>Maintainability: <strong className="text-foreground">{metrics.maintainability_index?.toFixed(1)}</strong></span>
          </div>
        )}
      </div>

      {/* Issues list */}
      {issues.length > 0 ? (
        <div className="space-y-1 max-h-64 overflow-y-auto custom-scrollbar border border-border/50 rounded-lg bg-card/50 p-2">
          {issues
            .filter((i: any) => i.type !== 'ai_overview')
            .map((issue: any, idx: number) => (
              <IssueRow key={idx} issue={issue} />
            ))}
          {issues.filter((i: any) => i.type !== 'ai_overview').length === 0 && (
            <div className="text-sm text-muted-foreground text-center py-4">No issues found in this analysis.</div>
          )}
        </div>
      ) : (
        <div className="text-sm text-muted-foreground text-center py-4 border border-border/50 rounded-lg bg-card/50">
          No detailed issue data available.
        </div>
      )}

      {/* Code preview */}
      {code && (
        <details className="mt-3 group">
          <summary className="text-xs text-muted-foreground cursor-pointer hover:text-foreground transition-colors flex items-center gap-1.5 select-none">
            <FileCode className="h-3.5 w-3.5" />
            View analyzed code
          </summary>
          <pre className="mt-2 text-xs font-mono text-foreground/80 bg-background border border-border rounded-lg p-3 overflow-x-auto max-h-48 leading-relaxed">
            {code}
          </pre>
        </details>
      )}

      {/* Export button */}
      <div className="mt-3 flex items-center gap-2">
        <button
          onClick={() => exportAnalysisMarkdown(analysis)}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-md border border-border bg-muted/30 text-muted-foreground hover:text-foreground hover:bg-muted/50 transition-colors"
        >
          <Download className="h-3.5 w-3.5" />
          Export Markdown
        </button>
        <button
          onClick={() => {
            const jsonStr = JSON.stringify(analysis?.originalAnalysis || {}, null, 2)
            const blob = new Blob([jsonStr], { type: 'application/json' })
            const url = URL.createObjectURL(blob)
            const a = document.createElement('a')
            a.href = url
            a.download = `intellireview-raw-${analysis?.id || Date.now()}.json`
            document.body.appendChild(a)
            a.click()
            document.body.removeChild(a)
            URL.revokeObjectURL(url)
          }}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-md border border-border bg-muted/30 text-muted-foreground hover:text-foreground hover:bg-muted/50 transition-colors"
        >
          <FileText className="h-3.5 w-3.5" />
          Export JSON
        </button>
      </div>
    </div>
  )
}

// --- DIALOG COMPONENT FOR MONGODB REPORTS ---
function ReportDialog({ scanId, onClose }: { scanId: string | null, onClose: () => void }) {
  const { data, isLoading, isError, error } = useScanReport(scanId);

  return (
    <Dialog.Root open={!!scanId} onOpenChange={(open: boolean) => !open && onClose()}>
      <Dialog.Portal>
        <Dialog.Overlay className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0" />
        <Dialog.Content className="fixed left-[50%] top-[50%] z-50 grid w-full max-w-4xl translate-x-[-50%] translate-y-[-50%] gap-4 border border-border bg-background p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 sm:rounded-lg md:w-full max-h-[85vh] flex flex-col">
          <div className="flex flex-col space-y-1.5">
            <Dialog.Title className="text-lg font-semibold leading-none tracking-tight">
               Scan Report Details
            </Dialog.Title>
            <Dialog.Description className="text-sm text-muted-foreground">
               Analysis Report for Scan ID: {scanId}
            </Dialog.Description>
          </div>
          
          <div className="flex-1 overflow-auto border border-border rounded-md bg-muted/10 p-4 relative min-h-[300px]">
             {isLoading ? (
               <div className="absolute inset-0 flex items-center justify-center flex-col gap-3 text-muted-foreground animate-pulse">
                  <FileCode className="h-8 w-8 opacity-40" />
                  <p className="text-sm">Loading scan report...</p>
               </div>
             ) : isError ? (
               <div className="absolute inset-0 flex items-center justify-center">
                  <p className="text-sm text-destructive">Failed to load report: {error instanceof Error ? error.message : 'Unknown error'}</p>
               </div>
             ) : data ? (
               <div className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                     <div className="bg-card p-3 rounded-lg border border-border">
                        <p className="text-xs text-muted-foreground mb-1">Project</p>
                        <p className="text-sm font-medium text-foreground">{data.project_name}</p>
                     </div>
                     <div className="bg-card p-3 rounded-lg border border-border">
                        <p className="text-xs text-muted-foreground mb-1">Scan Date</p>
                        <p className="text-sm font-medium text-foreground">{data.date}</p>
                     </div>
                     <div className="bg-card p-3 rounded-lg border border-border">
                        <p className="text-xs text-muted-foreground mb-1">Health Score</p>
                        <p className="text-sm font-medium text-foreground">{data.health_score}/100</p>
                     </div>
                     <div className="bg-card p-3 rounded-lg border border-border">
                        <p className="text-xs text-muted-foreground mb-1">Language</p>
                        <p className="text-sm font-medium text-foreground">{data.details?.language || 'Unknown'}</p>
                     </div>
                  </div>
                  {data.details?.issues && data.details.issues.length > 0 && (
                    <div>
                      <p className="text-xs text-muted-foreground mb-2 font-medium">Issues Found</p>
                      <div className="space-y-1 max-h-[200px] overflow-y-auto border border-border rounded-lg p-2 bg-card/50">
                        {data.details.issues
                          .filter((i: any) => i.type !== 'ai_overview')
                          .map((issue: any, idx: number) => (
                            <IssueRow key={idx} issue={issue} />
                          ))}
                      </div>
                    </div>
                  )}
                  <div>
                     <p className="text-xs text-muted-foreground mb-2 font-medium">Full Report JSON</p>
                     <pre className="text-xs font-mono whitespace-pre-wrap text-muted-foreground bg-background p-3 rounded border border-border overflow-auto max-h-[200px]">
                        {JSON.stringify(data, null, 2)}
                     </pre>
                  </div>
               </div>
             ) : (
               <div className="absolute inset-0 flex items-center justify-center">
                  <p className="text-sm text-muted-foreground">No report data available.</p>
               </div>
             )}
          </div>
          
          <Dialog.Close asChild>
            <button className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none">
              <X className="h-4 w-4" />
              <span className="sr-only">Close</span>
            </button>
          </Dialog.Close>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}

// --- TABLE CONFIGURATION ---
const columnHelper = createColumnHelper<TransformedScanData>()

export function ScanHistory() {
  const [page, setPage] = useState(0);
  const [selectedScanId, setSelectedScanId] = useState<string | null>(null);
  const [expandedRows, setExpandedRows] = useState<Set<string>>(new Set());
  
  const { data, isLoading, isError, error } = useScanHistory(page, 10);

  const toggleRow = (id: string) => {
    setExpandedRows(prev => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  const columns = [
    columnHelper.display({
      id: 'expand',
      cell: (props: any) => {
        const id = props.row.original.id
        const isExpanded = expandedRows.has(id)
        const hasIssues = (props.row.original.originalAnalysis?.issues || []).length > 0
        return hasIssues ? (
          <button 
            onClick={() => toggleRow(id)}
            className="p-1 rounded hover:bg-muted/50 transition-colors text-muted-foreground hover:text-foreground"
          >
            {isExpanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
          </button>
        ) : (
          <span className="p-1 text-muted-foreground/30"><ChevronRight className="h-4 w-4" /></span>
        )
      },
    }),
    columnHelper.accessor('project_name', {
      header: 'Source',
      cell: (info: any) => {
        const name = info.getValue()
        const lang = info.row.original.originalAnalysis?.language
        return (
          <div className="flex items-center gap-2">
            <FileCode className="h-4 w-4 text-muted-foreground shrink-0" />
            <div>
              <span className="font-medium text-foreground">{name}</span>
              {lang && <span className="ml-2 text-[10px] uppercase tracking-wider text-muted-foreground bg-muted/50 px-1.5 py-0.5 rounded">{lang}</span>}
            </div>
          </div>
        )
      },
    }),
    columnHelper.accessor('date', {
      header: 'Date',
      cell: (info: any) => (
        <div className="flex items-center gap-1.5 text-muted-foreground">
          <Clock className="h-3.5 w-3.5" />
          <span>{info.getValue()}</span>
        </div>
      ),
    }),
    columnHelper.accessor('health_score', {
      header: 'Health',
      cell: (info: any) => {
         const score = info.getValue()
         return (
           <div className="flex items-center gap-2">
              <div className="h-2 w-16 bg-muted rounded-full overflow-hidden">
                 <div 
                   className={`h-full transition-all ${score > 80 ? 'bg-green-500' : score > 50 ? 'bg-yellow-500' : 'bg-destructive'}`}
                   style={{ width: `${score}%` }}
                 />
              </div>
              <span className="text-xs font-mono">{score}</span>
           </div>
         )
      }
    }),
    columnHelper.display({
      id: 'issues_summary',
      header: 'Issues',
      cell: (props: any) => {
        const issues = props.row.original.originalAnalysis?.issues || []
        const nonOverview = issues.filter((i: any) => i.type !== 'ai_overview')
        if (nonOverview.length === 0) {
          return <span className="text-green-500 text-xs font-medium">✓ Clean</span>
        }
        const crits = nonOverview.filter((i: any) => i.severity === 'critical').length
        const highs = nonOverview.filter((i: any) => i.severity === 'high').length
        const others = nonOverview.length - crits - highs
        return (
          <div className="flex items-center gap-1.5">
            {crits > 0 && <SeverityBadge severity="critical" />}
            {highs > 0 && <SeverityBadge severity="high" />}
            {others > 0 && <span className="text-xs text-muted-foreground">+{others}</span>}
            {crits === 0 && highs === 0 && <SeverityBadge severity="medium" />}
          </div>
        )
      }
    }),
    columnHelper.accessor('technical_debt_hours', {
      header: 'Debt',
      cell: (info: any) => <span className="text-muted-foreground text-xs">{info.getValue()}h</span>,
    }),
    columnHelper.display({
      id: 'actions',
      cell: (props: any) => (
        <button 
           onClick={() => setSelectedScanId(props.row.original.id)}
           className="text-xs font-medium text-primary hover:text-primary/80 transition-colors flex items-center gap-1"
        >
           <Info className="h-3 w-3" /> Details
        </button>
      )
    })
  ]

  const safeData = data?.data || [];

  const table = useReactTable({
    data: safeData,
    columns,
    getCoreRowModel: getCoreRowModel(),
  })

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Analysis History</h1>
          <p className="text-muted-foreground">View past analyses with detailed issue breakdowns and metrics.</p>
        </div>
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <Shield className="h-4 w-4" />
          {safeData.length > 0 ? `${safeData.length} scans` : 'No scans yet'}
        </div>
      </div>

      <div className="border border-border rounded-lg bg-card overflow-hidden shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="bg-muted/50 text-muted-foreground border-b border-border uppercase text-[10px] tracking-wider">
              {table.getHeaderGroups().map((headerGroup: any) => (
                <tr key={headerGroup.id}>
                  {headerGroup.headers.map((header: any) => (
                    <th key={header.id} className="px-4 py-3 font-semibold">
                      {header.isPlaceholder
                        ? null
                        : flexRender(
                            header.column.columnDef.header,
                            header.getContext()
                          )}
                    </th>
                  ))}
                </tr>
              ))}
            </thead>
            <tbody className="divide-y divide-border/40">
              {isLoading && !data ? (
                 <tr>
                    <td colSpan={7} className="px-4 py-8 text-center text-muted-foreground">
                      <div className="flex items-center justify-center gap-2">
                        <RefreshCw className="h-4 w-4 animate-spin" />
                        Loading scan history...
                      </div>
                    </td>
                 </tr>
              ) : isError ? (
                 <tr>
                    <td colSpan={7} className="px-4 py-8 text-center text-destructive">
                       <div className="flex items-center justify-center gap-2">
                         <AlertTriangle className="h-4 w-4" />
                         Error loading history: {error instanceof Error ? error.message : 'Unknown error'}
                       </div>
                    </td>
                 </tr>
              ) : safeData.length === 0 ? (
                 <tr>
                    <td colSpan={7} className="px-4 py-12 text-center">
                      <div className="flex flex-col items-center gap-3 text-muted-foreground">
                        <FileCode className="h-10 w-10 opacity-30" />
                        <p className="font-medium">No analysis history yet</p>
                        <p className="text-sm">Upload a project or use the Review Engine to start analyzing code.</p>
                      </div>
                    </td>
                 </tr>
              ) : table.getRowModel().rows.map((row: any) => {
                const isExpanded = expandedRows.has(row.original.id)
                return (
                  <React.Fragment key={row.id || row.original?.id}>
                    <tr 
                      className={`hover:bg-muted/30 transition-colors cursor-pointer ${isExpanded ? 'bg-muted/20' : ''}`}
                      onClick={() => {
                        const hasIssues = (row.original.originalAnalysis?.issues || []).length > 0
                        if (hasIssues) toggleRow(row.original.id)
                      }}
                    >
                      {row.getVisibleCells().map((cell: any) => (
                        <td key={cell.id} className="px-4 py-3">
                          {flexRender(cell.column.columnDef.cell, cell.getContext())}
                        </td>
                      ))}
                    </tr>
                    {isExpanded && (
                      <tr>
                        <td colSpan={7} className="p-0">
                          <ExpandedDetail analysis={row.original} />
                        </td>
                      </tr>
                    )}
                  </React.Fragment>
                )
              })}
            </tbody>
          </table>
        </div>
        <div className="p-4 border-t border-border flex items-center justify-between text-sm bg-muted/10">
           <span className="text-muted-foreground font-medium">Page {page + 1}</span>
           <div className="flex gap-2">
              <button 
                onClick={() => setPage(p => Math.max(0, p - 1))}
                disabled={page === 0}
                className="px-3 py-1.5 border border-border rounded-md disabled:opacity-50 hover:bg-muted/50 transition-colors font-medium bg-background text-sm"
              >Previous</button>
              <button 
                onClick={() => setPage(p => p + 1)}
                disabled={safeData.length < 10}
                className="px-3 py-1.5 bg-secondary text-secondary-foreground rounded-md hover:bg-secondary/80 disabled:opacity-50 transition-colors font-medium text-sm"
              >Next</button>
           </div>
        </div>
      </div>
      
      <ReportDialog scanId={selectedScanId} onClose={() => setSelectedScanId(null)} />
    </div>
  )
}
