"""
AI-Generated Code Pattern Detector
====================================
Detects common mistakes and anti-patterns specifically found in code
generated by AI coding assistants (Claude, Copilot, ChatGPT, Cursor, etc.).

These patterns are rarely produced by experienced human developers but are
frequently observed in AI-generated code.
"""

import re
import ast
from typing import List, Dict


class AIPatternDetector:
    """Detect AI-generated code patterns and common AI coding mistakes."""

    def detect(self, code: str, filename: str = "unknown", language: str = "python") -> List[Dict]:
        """Run all AI-pattern checks on the given code."""
        issues = []
        lines = code.split('\n')

        # Language-agnostic checks (run on all code)
        issues.extend(self._check_placeholder_logic(lines))
        issues.extend(self._check_over_commenting(lines))
        issues.extend(self._check_copy_paste_drift(lines))
        issues.extend(self._check_dead_code_blocks(lines))
        issues.extend(self._check_excessive_error_swallowing(lines, language))
        issues.extend(self._check_hallucinated_constants(lines))

        # Language-specific checks
        if language == "python":
            issues.extend(self._check_python_ai_patterns(code, lines))
        elif language == "javascript":
            issues.extend(self._check_javascript_ai_patterns(code, lines))
        elif language in ("java", "cpp", "c"):
            issues.extend(self._check_typed_lang_ai_patterns(code, lines, language))

        return issues

    # ─── 1. Placeholder / TODO Logic ────────────────────────────────

    def _check_placeholder_logic(self, lines: List[str]) -> List[Dict]:
        """Detect incomplete placeholder logic left by AI generators."""
        issues = []
        patterns = [
            (r'\b(TODO|FIXME|HACK|XXX|PLACEHOLDER)\b', 'Unresolved TODO/placeholder found'),
            (r'raise\s+NotImplementedError', 'NotImplementedError left in code'),
            (r'pass\s*$', None),  # 'pass' needs context check
            (r'\.\.\.', None),   # Ellipsis needs context check
            (r'#\s*(implement|add|write|complete|fill)\s+(this|here|logic|code)', 
             'Placeholder comment indicating unfinished implementation'),
        ]

        empty_pass_count = 0
        for i, line in enumerate(lines, 1):
            stripped = line.strip()

            for pattern, msg in patterns:
                if pattern == r'pass\s*$' and re.match(pattern, stripped):
                    empty_pass_count += 1
                    if empty_pass_count >= 3:
                        issues.append({
                            "type": "ai_placeholder",
                            "severity": "high",
                            "line": i,
                            "message": f"Excessive 'pass' statements ({empty_pass_count}+) — likely AI-generated stubs",
                            "suggestion": "Replace placeholder 'pass' with actual implementation logic"
                        })
                    continue

                if pattern == r'\.\.\.':
                    if stripped == '...':
                        issues.append({
                            "type": "ai_placeholder",
                            "severity": "high",
                            "line": i,
                            "message": "Ellipsis '...' used as placeholder body",
                            "suggestion": "Replace with actual implementation"
                        })
                    continue

                if msg and re.search(pattern, line, re.IGNORECASE):
                    issues.append({
                        "type": "ai_placeholder",
                        "severity": "medium",
                        "line": i,
                        "message": msg,
                        "suggestion": "Complete the implementation before committing"
                    })

        return issues

    # ─── 2. Over-Commenting (AI Signature) ──────────────────────────

    def _check_over_commenting(self, lines: List[str]) -> List[Dict]:
        """Detect excessive obvious comments — a hallmark of AI-generated code."""
        issues = []
        code_lines = 0
        comment_lines = 0
        obvious_comments = []

        obvious_patterns = [
            r'#\s*(import|define|set|create|initialize|declare|assign|return|print|call)\s+\w+',
            r'#\s*(this|the)\s+(function|method|class|variable|loop|line)\s+',
            r'//\s*(import|define|set|create|initialize|declare|assign|return|print|call)\s+\w+',
            r'//\s*(this|the)\s+(function|method|class|variable|loop|line)\s+',
        ]

        for i, line in enumerate(lines, 1):
            stripped = line.strip()
            if not stripped:
                continue
            if stripped.startswith(('#', '//')):
                comment_lines += 1
                for pat in obvious_patterns:
                    if re.match(pat, stripped, re.IGNORECASE):
                        obvious_comments.append(i)
                        break
            else:
                code_lines += 1

        # Flag if >40% of lines are comments AND many are obvious
        if code_lines > 10 and comment_lines > 0:
            ratio = comment_lines / (code_lines + comment_lines)
            if ratio > 0.40 and len(obvious_comments) >= 5:
                issues.append({
                    "type": "ai_over_commenting",
                    "severity": "low",
                    "line": obvious_comments[0],
                    "message": (f"Excessive obvious comments detected "
                                f"({comment_lines}/{code_lines + comment_lines} lines, "
                                f"{len(obvious_comments)} trivial). "
                                f"This is a common AI code pattern."),
                    "suggestion": "Remove comments that simply restate the code. "
                                  "Keep only explanatory comments about 'why', not 'what'."
                })

        return issues

    # ─── 3. Copy-Paste Drift ────────────────────────────────────────

    def _check_copy_paste_drift(self, lines: List[str]) -> List[Dict]:
        """Detect near-identical repeated code blocks — AI tends to copy-paste
        with minor variations instead of refactoring into a function."""
        issues = []

        # Normalize lines (strip whitespace, ignore empty/comments)
        normalized = []
        for i, line in enumerate(lines, 1):
            stripped = line.strip()
            if stripped and not stripped.startswith(('#', '//', '/*', '*')):
                normalized.append((i, stripped))

        # Check for repeated 3-line windows
        window_size = 3
        seen_windows = {}

        for idx in range(len(normalized) - window_size + 1):
            window = tuple(normalized[idx + j][1] for j in range(window_size))
            if window in seen_windows:
                first_line = seen_windows[window]
                current_line = normalized[idx][0]
                # Only report once per duplicate
                if current_line - first_line > window_size:
                    issues.append({
                        "type": "ai_copy_paste",
                        "severity": "medium",
                        "line": current_line,
                        "message": (f"Duplicate code block (lines {first_line}-{first_line + window_size - 1} "
                                    f"repeated at {current_line}-{current_line + window_size - 1})"),
                        "suggestion": "Extract into a reusable function to reduce repetition"
                    })
            else:
                seen_windows[window] = normalized[idx][0]

        # Cap at 5 issues to avoid noise
        return issues[:5]

    # ─── 4. Dead / Unreachable Code ─────────────────────────────────

    def _check_dead_code_blocks(self, lines: List[str]) -> List[Dict]:
        """Detect dead code patterns commonly left by AI generators."""
        issues = []

        for i, line in enumerate(lines, 1):
            stripped = line.strip()

            # Code after return/break/continue
            if i < len(lines) and stripped in ('return', 'return;', 'break', 'break;', 'continue', 'continue;'):
                next_idx = i  # 0-indexed next line
                while next_idx < len(lines):
                    next_stripped = lines[next_idx].strip()
                    if next_stripped and not next_stripped.startswith(('#', '//', '}', 'except', 'catch', 'finally', 'else', 'elif', 'case')):
                        issues.append({
                            "type": "ai_dead_code",
                            "severity": "medium",
                            "line": next_idx + 1,
                            "message": f"Unreachable code after '{stripped}' on line {i}",
                            "suggestion": "Remove unreachable code or restructure control flow"
                        })
                        break
                    break

            # if False / if 0 blocks
            if re.match(r'if\s+(False|0|false)\s*:', stripped) or re.match(r'if\s*\(\s*(false|0)\s*\)', stripped):
                issues.append({
                    "type": "ai_dead_code",
                    "severity": "medium",
                    "line": i,
                    "message": "Dead code: condition is always false",
                    "suggestion": "Remove the dead code block entirely"
                })

        return issues[:5]

    # ─── 5. Error Swallowing (Security Theater) ─────────────────────

    def _check_excessive_error_swallowing(self, lines: List[str], language: str) -> List[Dict]:
        """Detect bare except/catch blocks that silently swallow errors."""
        issues = []
        swallow_count = 0

        for i, line in enumerate(lines, 1):
            stripped = line.strip()

            if language == "python":
                if stripped == 'except:' or re.match(r'except\s+Exception\s*(as\s+\w+)?:', stripped):
                    # Check if next non-empty line is just 'pass'
                    for j in range(i, min(i + 3, len(lines))):
                        next_s = lines[j].strip()
                        if next_s == 'pass':
                            swallow_count += 1
                            break
            elif language == "javascript":
                if re.match(r'catch\s*\(\w+\)\s*\{', stripped):
                    # Check if catch body is empty or just has a comment
                    if i < len(lines):
                        next_s = lines[i].strip() if i < len(lines) else ''
                        if next_s in ('', '}') or next_s.startswith('//'):
                            swallow_count += 1

        if swallow_count >= 2:
            issues.append({
                "type": "ai_error_swallowing",
                "severity": "high",
                "line": 1,
                "message": (f"{swallow_count} empty exception handlers found. "
                            f"AI-generated code often wraps everything in try/catch "
                            f"but silently discards errors."),
                "suggestion": "Log errors, re-raise when appropriate, or handle specific exception types"
            })

        return issues

    # ─── 6. Hallucinated Constants / Magic Values ───────────────────

    def _check_hallucinated_constants(self, lines: List[str]) -> List[Dict]:
        """Detect suspicious magic numbers/strings that may be hallucinated."""
        issues = []
        magic_count = 0

        for i, line in enumerate(lines, 1):
            stripped = line.strip()
            if stripped.startswith(('#', '//', '/*', '*')):
                continue

            # Suspicious URL patterns (common AI hallucination)
            url_matches = re.findall(r'https?://[^\s\'"]+', stripped)
            for url in url_matches:
                if any(word in url.lower() for word in ['example.com', 'placeholder', 'your-', 'xxx', 'changeme']):
                    issues.append({
                        "type": "ai_hallucinated",
                        "severity": "high",
                        "line": i,
                        "message": f"Likely placeholder URL: {url}",
                        "suggestion": "Replace with actual production URL"
                    })

            # Suspicious API key patterns
            if re.search(r'["\']sk-[a-zA-Z0-9]{20,}["\']', stripped):
                issues.append({
                    "type": "ai_hallucinated",
                    "severity": "critical",
                    "line": i,
                    "message": "Hardcoded API key detected (possibly hallucinated by AI)",
                    "suggestion": "Use environment variables for API keys, never hardcode them"
                })

        return issues

    # ─── Python-Specific AI Patterns ────────────────────────────────

    def _check_python_ai_patterns(self, code: str, lines: List[str]) -> List[Dict]:
        """Python-specific AI code detection."""
        issues = []

        try:
            tree = ast.parse(code)
        except SyntaxError:
            return issues

        # Check for unnecessary type conversions (AI habit)
        for node in ast.walk(tree):
            if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
                if node.func.id == 'str' and len(node.args) == 1:
                    arg = node.args[0]
                    if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
                        issues.append({
                            "type": "ai_redundant",
                            "severity": "low",
                            "line": node.lineno,
                            "message": "Redundant str() call on a string literal",
                            "suggestion": "Remove unnecessary type conversion"
                        })
                if node.func.id == 'int' and len(node.args) == 1:
                    arg = node.args[0]
                    if isinstance(arg, ast.Constant) and isinstance(arg.value, int):
                        issues.append({
                            "type": "ai_redundant",
                            "severity": "low",
                            "line": node.lineno,
                            "message": "Redundant int() call on an integer literal",
                            "suggestion": "Remove unnecessary type conversion"
                        })

        # Check for overly broad imports (AI imports everything)
        import_count = 0
        used_names = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                import_count += len(node.names)
            elif isinstance(node, ast.ImportFrom):
                import_count += len(node.names)
            elif isinstance(node, ast.Name):
                used_names.add(node.id)

        if import_count > 15:
            issues.append({
                "type": "ai_over_engineering",
                "severity": "low",
                "line": 1,
                "message": f"Excessive imports ({import_count}) — AI tends to import more than needed",
                "suggestion": "Review imports and remove unused ones"
            })

        return issues

    # ─── JavaScript-Specific AI Patterns ────────────────────────────

    def _check_javascript_ai_patterns(self, code: str, lines: List[str]) -> List[Dict]:
        """JavaScript-specific AI code detection."""
        issues = []

        # console.log left in production code (AI debugging artifact)
        console_count = 0
        for i, line in enumerate(lines, 1):
            if 'console.log(' in line and not line.strip().startswith('//'):
                console_count += 1

        if console_count >= 5:
            issues.append({
                "type": "ai_debug_artifact",
                "severity": "medium",
                "line": 1,
                "message": f"{console_count} console.log() calls found — likely AI debugging artifacts",
                "suggestion": "Remove console.log statements or replace with a proper logger"
            })

        # Mixing async patterns (AI confusion between callbacks, promises, async/await)
        has_callback = bool(re.search(r'function\s*\([^)]*callback', code))
        has_promise = '.then(' in code
        has_async = 'async ' in code
        pattern_count = sum([has_callback, has_promise, has_async])

        if pattern_count >= 3:
            issues.append({
                "type": "ai_inconsistency",
                "severity": "medium",
                "line": 1,
                "message": "Mixed async patterns: callbacks, promises, AND async/await detected in same file",
                "suggestion": "Standardize on async/await for consistency"
            })

        return issues

    # ─── Typed Language AI Patterns (Java/C/C++) ────────────────────

    def _check_typed_lang_ai_patterns(self, code: str, lines: List[str], language: str) -> List[Dict]:
        """Java/C/C++ specific AI code detection."""
        issues = []

        # Over-engineering: excessive class/interface count in a single file
        class_count = len(re.findall(r'\bclass\s+\w+', code))
        interface_count = len(re.findall(r'\binterface\s+\w+', code))
        total = class_count + interface_count

        if total >= 5:
            issues.append({
                "type": "ai_over_engineering",
                "severity": "medium",
                "line": 1,
                "message": f"{total} classes/interfaces in a single file — AI tends to over-engineer",
                "suggestion": "Split into separate files following single-responsibility principle"
            })

        # Unused variables in Java (common AI pattern)
        if language == "java":
            declared_vars = re.findall(r'(?:int|String|double|float|boolean|long)\s+(\w+)\s*[=;]', code)
            for var in declared_vars:
                # Count usages (excluding declaration)
                usage_count = len(re.findall(r'\b' + re.escape(var) + r'\b', code)) - 1
                if usage_count <= 0:
                    line_num = 1
                    for i, line in enumerate(lines, 1):
                        if re.search(r'\b' + re.escape(var) + r'\b', line):
                            line_num = i
                            break
                    issues.append({
                        "type": "ai_unused_var",
                        "severity": "low",
                        "line": line_num,
                        "message": f"Variable '{var}' declared but never used",
                        "suggestion": "Remove unused variables"
                    })

        return issues[:5]
